config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}
  devise_for :customers, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

 
 namespace :admin do
   get  "/" => "homes#top"
   resources :items, only: [:index, :new, :create, :show, :edit, :update]
   resources :genres, only: [:index, :create, :edit, :update]
   resources :customers, only: [:index, :show, :edit, :update]
   resources :orders, only: [:show, :update]
   resources :ordered_products, only: [:update]
 end
 scope module: 'public' do
  get "/" => "homes#top"
  get "/about" => "homes#about", as: "about"
 resources :items, only: [:index, :show]
 get "/customers/my_page" => "customers#show"
 get "/customers/information/edit" => "customers#edit"
 patch "/customers/information" => "customers#update"
 get "/customers/unsubscribe" => "customers#unsubscribe" #顧客の退会確認画面
 patch "/customers/withdrawal" => "customers#withdrawal", as: "withdrawal_customers"#顧客の退会処理(ステータスの更新)
 put "/customers/withdrawal" => "customers#withdrawal"
 resources :cart_items, only: [:index, :update, :create, :destroy]
 delete "/cart_items" => "cart_items#destroy_all" #カート内商品データ削除(全て)
 resources :orders, only: [:new, :create, :index, :show]
 post "/orders/confirm" => "orders#confirm" #注文情報確認画面
 get "/orders/complete" => "orders#complete" #注文完了画面
 resources :addresses, only: [:index, :edit, :create, :update, :destroy]
end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
 belongs_to :item
 belongs_to :customer
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :addresses, dependent: :destroy
  has_many :order_informations, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  def name
    last_name + first_name
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :ordered_products, dependent: :destroy
  belongs_to :genre
  has_one_attached :image
  def add_tax_price
        (self.price * 1.08).round
  end
end

app/models/order_information.rb
class OrderInformation < ApplicationRecord
  belongs_to :customer
	has_many :ordered_products, dependent: :destroy
	
	enum method_of_payment: { クレジットカード: 0, 銀行振込: 1}
	enum status: { 入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4}
end

app/models/ordered_product.rb
class OrderedProduct < ApplicationRecord
  belongs_to :item
  belongs_to :order_information
  
  enum making_status: {製作不可: 0, 製作待ち: 1, 製作中: 2, 製作完了: 3}
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end
  
  def show
    @customer = Customer.find(params[:id])
  end
  
  def edit
    @customer = Customer.find(params[:id])
  end
  
  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path
  end
  
  private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :phone_number, :email, :is_active)
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
  	@genres = Genre.all
  end
  
  def create
    @genre = Genre.new(params_genre)
  	if @genre.save
  		redirect_to admin_genres_path
  	else
  		@genres = Genre.all
  		render "admin/genres/index"
  	end
  end
  
  def edit
    @genre = Genre.find(params[:id])
  end
  
  def update
    @genre = Genre.find(params[:id])
    if @genre.update(params_genre)
        
      redirect_to admin_genres_path
    else
      render "admin/genres/edit"
    end
  end
  
  private
  def params_genre
    params.require(:genre).permit(:name, :status)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @order_informations = OrderInformation.all
    @ordered_products = OrderedProduct.all
  end  
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.page(params[:page])
  end
  
  def new
    @item = Item.new
  end
  
  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item)
    else
      render :new
    end
  end
  
  def show
    @item = Item.find(params[:id])
    @genre = Genre.find(@item.genre_id)
  end
  
  def edit
    @item = Item.find(params[:id])
  end
  
  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path
  end
  
  private
  def item_params
    params.require(:item).permit(:name, :genre_id, :price, :is_active, :image, :introduction)
  end
  def params_genre
    params.require(:genre).permit(:name, :status)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order_information = OrderInformation.find(params[:id])
    @ordered_products = OrderedProduct.all
  end
  
  def update
    @order_information = OrderInformation.find(params[:id])
    @order_information.update(order_params)
    if params[:order][:status] == "入金確認"
         @ordered_products.each do |ordered_products|
            ordered_products.update!(create_status: 1)
         end
    end
      redirect_to admin_order_path(@order)
  end
  
  private
   def order_params
      params.require(:order).permit(:customer_id, :shipping_postal_code, :shipping_address, :shipping_name, :method_of_payment, :status, :postage, :billing_amount)
   end

end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 def after_sign_in_path_for(resource)
        case resource
        when Admin
            root_path
        when Customer
            customers_my_page_path # ログイン後に遷移するpathを設定
        end
 end

  
  private

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,keys:[:email])
    end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
      <h5><%= @customer.name %>さんの会員情報編集</h5>
    <%= form_for @customer, url: admin_customer_path(@customer) do |f| %>
      <table class="admin_edit_customer">
        <tr>
          <th>会員ID</th>
          <td><%= @customer.id %></td>
        </tr>
        <tr>
          <th>氏名</th>
          <td>
            <%= f.text_field :last_name %>
            <%= f.text_field :first_name %>
          </td>
        </tr>
        <tr>
          <th>フリガナ</th>
          <td>
            <%= f.text_field :last_name_kana %>
            <%= f.text_field :first_name_kana %>
          </td>
        </tr>
        <tr>
          <th>郵便番号</th>
          <td><%= f.number_field :postal_code %></td>
        </tr>
        <tr>
          <th>住所</th>
          <td><%= f.text_field :address %></td>
        </tr>
        <tr>
          <th>電話番号</th>
          <td><%= f.phone_field :telephone_number %></td>
        </tr>
        <tr>
          <th>メールアドレス</th>
          <td><%= f.email_field :email %><td>
        </tr>
        <tr>
          <th>会員ステータス</th>
          <td>
            <%= f.radio_button :is_active, :true %>
            <%= f.label :is_active, "有効", {value: :true, style: "display: inline-block;"} %>
            <%= f.radio_button :is_active, :false %>
            <%= f.label :is_active, "退会", {value: :false, style: "display: inline-block;"} %>
          </td>
        </tr>
          <tr>
            <td><%= f.submit "変更を保存", class: "btn btn-success" %></td>
          </tr>
      </table>
    <% end %>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-3">
      <h5>会員一覧</h5>
    </div>
  </div>
  <div class="row">
        <div class="col-lg-offset-1 col-lg-10">
            <table class="table">
            <thead>
                <tr class="active">
                    <th>会員ID</th>
                    <th>氏名</th>
                    <th>メールアドレス</th>
                    <th>ステータス</th>
                </tr>
            </thead>
            <tbody>
                <% @customers.each do |customer| %>
                <tr>
                        <td><%= customer.id %></td>
                        <td><%= link_to customer.name, admin_customer_path(customer) %>
                        <td><%= customer.email %></td>
                        <td>
                            <% if customer.is_active == true %>
                                有効
                            <% else %>
                                退会
                            <% end %>
                        </td>
                </tr>
                <% end %>
            </tbody>
            </table>
        </div>
    </div>
</div>
 

app/views/admin/customers/show.html.erb
<div class="container">
            <h5><%= @customer.name %>さんの会員情報</h5>
    <div class="row">
        <div class="col-lg-3">
            <table class="admin_show_customer">
                <tr class="active">
                    <th>会員ID</th>
                    <td><%= @customer.id %></tb>
                </th> 
               <tr>
                    <th>氏名</th>
                    <td><%= @customer.last_name %> <%= @customer.first_name %></td>
                </tr>
                <tr>
                    <th>フリガナ</th>
                    <td><%= @customer.last_name_kana %> <%= @customer.first_name_kana %></td>
                </tr>
                <tr>
                    <th>郵便番号</th>
                    <td><%= @customer.postal_code %></td>
                </tr>
                <tr>
                    <th>住所</th>
                    <td><%= @customer.address %></td>
                </tr>
                <tr>
                    <th>電話番号</th>
                    <td><%= @customer.telephone_number %></td>
                </tr>
                <tr>
                    <th>メールアドレス</th>
                    <td><%= @customer.email %></td>
                </tr>
                <tr>
                  <th>会員ステータス</th>
                  <td>
                    <% if @customer.is_active == true %>
                    有効
                    <% else %>
                    退会
                    <% end %>
                  </td>
                </tr>
            </table>
        </div>
    </div>
      <%= link_to "編集する", edit_admin_customer_path, class: "btn btn-success" %>
      <%= link_to "注文履歴一覧を見る", admin_url, class: "btn btn-primary" %>
</div> 