config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}
  devise_for :customers, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

 
 namespace :admin do
   get  "/" => "homes#top"
   resources :items, only: [:index, :new, :create, :show, :edit, :update]
   resources :genres, only: [:index, :create, :edit, :update]
   resources :customers, only: [:index, :show, :edit, :update]
   resources :orders, only: [:show, :update]
   resources :ordered_products, only: [:update]
 end
 scope module: 'public' do
  get "/" => "homes#top"
  get "/about" => "homes#about", as: "about"
 resources :items, only: [:index, :show]
 get "/customers/my_page" => "customers#show"
 get "/customers/information/edit" => "customers#edit"
 patch "/customers/information" => "customers#update"
 get "/customers/unsubscribe" => "customers#unsubscribe" #顧客の退会確認画面
 patch "/customers/withdrawal" => "customers#withdrawal", as: "withdrawal_customers"#顧客の退会処理(ステータスの更新)
 put "/customers/withdrawal" => "customers#withdrawal"
 resources :cart_items, only: [:index, :update, :create, :destroy]
 delete "/cart_items" => "cart_items#destroy_all" #カート内商品データ削除(全て)
 resources :orders, only: [:new, :create, :index, :show]
 post "/orders/confirm" => "orders#confirm" #注文情報確認画面
 get "/orders/complete" => "orders#complete" #注文完了画面
 resources :addresses, only: [:index, :edit, :create, :update, :destroy]
end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
 belongs_to :item
 belongs_to :customer
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :addresses, dependent: :destroy
  has_many :order_informations, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  def name
    last_name + first_name
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :ordered_products, dependent: :destroy
  belongs_to :genre
  has_one_attached :image
  def add_tax_price
        (self.price * 1.08).round
  end
end

app/models/order_information.rb
class OrderInformation < ApplicationRecord
  belongs_to :customer
	has_many :ordered_products, dependent: :destroy
	
	enum method_of_payment: { クレジットカード: 0, 銀行振込: 1}
	enum status: { 入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4}
end

app/models/ordered_product.rb
class OrderedProduct < ApplicationRecord
  belongs_to :item
  belongs_to :order_information
  
  enum making_status: {製作不可: 0, 製作待ち: 1, 製作中: 2, 製作完了: 3}
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
  	@genres = Genre.all
  end
  
  def create
    @genre = Genre.new(params_genre)
  	if @genre.save
  		redirect_to admin_genres_path
  	else
  		@genres = Genre.all
  		render "admin/genres/index"
  	end
  end
  
  def edit
    @genre = Genre.find(params[:id])
  end
  
  def update
    @genre = Genre.find(params[:id])
    if @genre.update(params_genre)
        
      redirect_to admin_genres_path
    else
      render "admin/genres/edit"
    end
  end
  
  private
  def params_genre
    params.require(:genre).permit(:name, :status)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @order_informations = OrderInformation.all
    @ordered_products = OrderedProduct.all
  end  
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.page(params[:page])
  end
  
  def new
    @item = Item.new
  end
  
  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item)
    else
      render :new
    end
  end
  
  def show
    @item = Item.find(params[:id])
    @genre = Genre.find(@item.genre_id)
  end
  
  def edit
    @item = Item.find(params[:id])
  end
  
  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path
  end
  
  private
  def item_params
    params.require(:item).permit(:name, :genre_id, :price, :is_active, :image, :introduction)
  end
  def params_genre
    params.require(:genre).permit(:name, :status)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order_information = OrderInformation.find(params[:id])
    @ordered_products = OrderedProduct.all
  end
  
  def update
    @order_information = OrderInformation.find(params[:id])
    @order_information.update(order_params)
    if params[:order][:status] == "入金確認"
         @ordered_products.each do |ordered_products|
            ordered_products.update!(create_status: 1)
         end
    end
      redirect_to admin_order_path(@order)
  end
  
  private
   def order_params
      params.require(:order).permit(:customer_id, :shipping_postal_code, :shipping_address, :shipping_name, :method_of_payment, :status, :postage, :billing_amount)
   end

end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 def after_sign_in_path_for(resource)
        case resource
        when Admin
            root_path
        when Customer
            customers_my_page_path # ログイン後に遷移するpathを設定
        end
 end

  
  private

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,keys:[:email])
    end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-3">
      <h5>注文履歴一覧</h5>
    </div>
  </div>
  <div class="row">
     <div class="col-lg-offset-1 col-lg-10">
       <table class="table">
            <thead>
                <tr class="active">
                    <th>購入日時</th>
                    <th>購入者</th>
                    <th>注文個数</th>
                    <th>注文ステータス</th>
                </tr>
            </thead>
            <tbody>
              <% @order_informations.each do |order_information| %>
  　　　        　　<tr>
                  <td><%= link_to order_information.created_at, admin_order_path(order_information) %></td>
                  <td><%= order_information.customer.name %></td>
                  <% @ordered_products.each do |ordered_product| %>
                  <td><%= ordered_products.amount %></td>
                  <% end %>
                  <td><%= order_information.status %></td>
                </tr>
　　　　　    <% end %>
            </tbody>
       </table>    
     </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-3">
			<h3>注文履歴詳細</h3>
		</div>
	</div>
	<div class="row">
		<div class="col-lg-offset-1 col-lg-6">
			<div class="row"><span class="orders">購入者   <small><%=link_to @order_information.customer.name, admin_customer_path(@order_information.customer) %></small></span></div>
			<div class="row"><span class="orders">注文日   <small><%= @order_information.created_at %></small></span></div>
			<div class="row"><span class="orders">配送先   <small><%= @order_information.shipping_postal_code %><%= @order_information.shipping_address %></br><%= @order_information.shipping_name %></small></span></div>
			<div class="row"><span class="orders">支払方法    <small><%= @order_information.method_of_payment %></small></span></div>
			<div class="row"><span class="orders">注文ステータス</span>
			<%= form_with model:@order, url: admin_order_path(@order_information) do |f|%>
				<%= f.select :status ,OrderInformation.statuses.keys.to_a, {},{include_blank: @order_information.status}  %>
				<%= f.submit '更新',class: 'btn btn-success' %>
			<% end %></div>
		</div>
	</div>
	<div class="col-lg-8">
	<table class="table">
	<tr class="active">
		<th>商品名</th>
		<th>単価（税込）</th>
		<th>数量</th>
		<th>小計</th>
		<th>製作ステータス</th>
	</tr>
		<% @order_products.each do |order_product| %>
			<tr>
				<td><%= order_product.item.name %></td>
				<td><%= include_tax(order_product.item.price) %></td>
				<td><%= order_product.count %></td>
				<td><%= include_tax(order_product.item.price) * order_product.count %></td>
				<td>
					<%= form_with model:order_product, url: admin_order_product_path(order_product) do |f|%>
						<%= f.select :making_status ,OrderProduct.making_statuses.keys.to_a, {},{include_blank: order_product.making_status} %>
						<%= f.submit '更新',class: 'btn btn-success' %>
					<% end %>
				</td>
			</tr>
		<% end %>
	</table>
	</div>
<div class="col-lg-4">
<dl class="dl-horizontal orders">
	<dt>商品合計</dt>  <dd><%= @order.billing_amount - @order_information.postage %>円</dd>
	<dt>送料</dt>  <dd><%= @order_information.postage %>円</dd>
	<dt>請求合計金額</dt>  <dd><%= @order.billing_amount %>円</dd>
</dl>
</div>
</div>