config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}
  devise_for :customers, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

 
 namespace :admin do
   get  "/" => "homes#top"
   resources :items, only: [:index, :new, :create, :show, :edit, :update]
   resources :genres, only: [:index, :create, :edit, :update]
   resources :customers, only: [:index, :show, :edit, :update]
   resources :orders, only: [:show, :update]
   resources :ordered_products, only: [:update]
 end
 scope module: 'public' do
  get "/" => "homes#top"
  get "/about" => "homes#about", as: "about"
 resources :items, only: [:index, :show]
 get "/customers/my_page" => "customers#show"
 get "/customers/information/edit" => "customers#edit"
 patch "/customers/information" => "customers#update"
 get "/customers/unsubscribe" => "customers#unsubscribe" #顧客の退会確認画面
 patch "/customers/withdrawal" => "customers#withdrawal", as: "withdrawal_customers"#顧客の退会処理(ステータスの更新)
 put "/customers/withdrawal" => "customers#withdrawal"
 resources :cart_items, only: [:index, :update, :create, :destroy]
 delete "/cart_items" => "cart_items#destroy_all" #カート内商品データ削除(全て)
 resources :orders, only: [:new, :create, :index, :show]
 post "/orders/confirm" => "orders#confirm" #注文情報確認画面
 get "/orders/complete" => "orders#complete" #注文完了画面
 resources :addresses, only: [:index, :edit, :create, :update, :destroy]
end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
 belongs_to :item
 belongs_to :customer
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :addresses, dependent: :destroy
  has_many :order_informations, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  def name
    last_name + first_name
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :ordered_products, dependent: :destroy
  belongs_to :genre
  has_one_attached :image
  def add_tax_price
        (self.price * 1.08).round
  end
end

app/models/order_information.rb
class OrderInformation < ApplicationRecord
  belongs_to :customer
	has_many :ordered_products, dependent: :destroy
	
	enum method_of_payment: { クレジットカード: 0, 銀行振込: 1}
	enum status: { 入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4}
end

app/models/ordered_product.rb
class OrderedProduct < ApplicationRecord
  belongs_to :item
  belongs_to :order_information
  
  enum making_status: {製作不可: 0, 製作待ち: 1, 製作中: 2, 製作完了: 3}
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
  	@genres = Genre.all
  end
  
  def create
    @genre = Genre.new(params_genre)
  	if @genre.save
  		redirect_to admin_genres_path
  	else
  		@genres = Genre.all
  		render "admin/genres/index"
  	end
  end
  
  def edit
    @genre = Genre.find(params[:id])
  end
  
  def update
    @genre = Genre.find(params[:id])
    if @genre.update(params_genre)
        
      redirect_to admin_genres_path
    else
      render "admin/genres/edit"
    end
  end
  
  private
  def params_genre
    params.require(:genre).permit(:name, :status)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @order_informations = OrderInformation.all
    @ordered_products = OrderedProduct.all
  end  
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.page(params[:page])
  end
  
  def new
    @item = Item.new
  end
  
  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item)
    else
      render :new
    end
  end
  
  def show
    @item = Item.find(params[:id])
    @genre = Genre.find(@item.genre_id)
  end
  
  def edit
    @item = Item.find(params[:id])
  end
  
  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path
  end
  
  private
  def item_params
    params.require(:item).permit(:name, :genre_id, :price, :is_active, :image, :introduction)
  end
  def params_genre
    params.require(:genre).permit(:name, :status)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order_information = OrderInformation.find(params[:id])
    @ordered_products = OrderedProduct.all
  end
  
  def update
    @order_information = OrderInformation.find(params[:id])
    @order_information.update(order_params)
    if params[:order][:status] == "入金確認"
         @ordered_products.each do |ordered_products|
            ordered_products.update!(create_status: 1)
         end
    end
      redirect_to admin_order_path(@order)
  end
  
  private
   def order_params
      params.require(:order).permit(:customer_id, :shipping_postal_code, :shipping_address, :shipping_name, :method_of_payment, :status, :postage, :billing_amount)
   end

end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 def after_sign_in_path_for(resource)
        case resource
        when Admin
            root_path
        when Customer
            customers_my_page_path # ログイン後に遷移するpathを設定
        end
 end

  
  private

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,keys:[:email])
    end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/ordered_products_helper.rb
module Admin::OrderedProductsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-3">
        	<h5>ジャンル編集</h5>
            <br>
        </div>
    </div>
    <%= form_for @genre,url: admin_genre_path(@genre.id) do |f| %>
        <div class="row">
            <label class="col-md-1 col-md-offset-1">ジャンル名</label>
                <div class="col-md-2">
                    <%= f.text_field :name %>
                </div>
                <div class="col-md-3">
                    <div class="col-md-6">
                        <%= f.submit "変更を保存",class: "btn btn-success" %>
                    </div>
                </div>
            </label>    
        </div>
    <% end %>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-3">
			<h5>ジャンル一覧・追加</h5>
		</div>
	</div>
	<%= form_for @genre,url: admin_genres_path, method: :post do |f| %>
		<div class="col-lg-4">
		  <table class="table" style="margin-top: 40px">
			<tr class="active">
				<th>ジャンル名</th>
				<th><%= f.text_field :name %></th>
				<th><%= f.submit "新規登録",class: "btn btn-success" %></th>
			</tr>
			</table>
		</div>
	<% end %>
	
	<!--ジャンル一覧表示-->
	<div class="row">
		<div class="col-md-5 col-md-offset-1">
			<table class="table">
				<tr class="admin-genre-index-trheader">
					<th>ジャンル</th>
					<th></th>
				</tr>


				<% @genres.each do |genre| %>
				<tr class="table-box">
					<td><%= genre.name %></td>
		
					<td><%= link_to "編集する",edit_admin_genre_path(genre.id), class: "btn btn-success" %></td>
				</tr>
				<% end %>
			</table>
		</div>
	</div>

app/views/admin/items/edit.html.erb
<div class="container">
<h5>商品編集</h5>
<div class="row">
<div class="col-xs-9">
<%= form_for @item, url: admin_item_path(@item) do |f| %>
    <div class="form-group has-icon">
      <%= f.label :image, "商品画像" %><br />
      <%= f.file_field :image, accept: "image/*" %>
    </div>
    <div class="form-group has-icon">
      <%= f.label :name, "商品名" %>
      <%= f.text_field :name, class:"form-control" %>
    </div>
    <div class="form-group has-icon">
      <%= f.label :introduction, "商品説明" %>
      <%= f.text_area :introduction, class:"form-control" %>
    </div>
    <div class="form-group has-icon">
      <%= f.label :genre_id, "ジャンル" %><br />
      <%= f.select :genre_id, [["ケーキ", "1"], ["キャンディ", "2"]], include_blank: "選択して下さい" %>
    </div>
    <div class="form-group has-icon">
      <%= f.label :price, "値段(税抜き)" %>
      <%= f.text_field :price, class:"form-control" %>
    </div>
    <div class="form-group has-icon">
      <%= f.radio_button :is_active, :true, checked: "checked"%>
       <%= f.label :is_active, "販売中", {value: :"true", style: "display: inline-block;"} %>
       <%= f.radio_button :is_active, :false %>
       <%= f.label :is_active, "販売停止中", {value: :"false", style: "display: inline-block;"} %>
    </div>
    <%= f.submit "変更を保存", class:"btn btn-success" %>
<% end %>
</div>
</div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
 <div class="row">
  <div class="col-lg-3">
   <h5>商品一覧</h5>
  </div>
  <div class="col-lg-8">
    <%= link_to new_admin_item_path do %>
       <span class="item-plus"><i class="fas fa-plus-circle"></i></span>
    <% end %>  
  </div>
  
  <div class="col-lg-offset-1 col-lg-10">
   <table class="table table-striped bg-light">
   <tr>
     <th>商品ID</th>
     <th>商品名</th>
     <th>税抜価格</th>
     <th>ジャンル</th>
     <th>ステータス</th>
   </tr>
   <% @items.each do |item| %>
     <tr>
       <td><%= item.id %></td>
       <td><%= link_to item.name, admin_item_path(item) %></td>
       <td><%= item.price %></td>
       <td>
         <% genre = Genre.find(item.genre_id) %>
         <%= genre.name %>  
       </td>
       <td>
         <% if item.is_active == true %>
             <p>販売中</p>
         <% else %>
             <p>販売停止中</p>
         <% end %>    
       </td>
     </tr>
   <% end %>
   </table>
  </div>
 </div>
 <div class="col-lg-12">
   <%= paginate @items %>
 </div>
</div> 

app/views/admin/items/new.html.erb
<div class="container">
<h5>商品登録</h5>
<div class="row">
<div class="col-xs-9">
<%= form_for @item, :url => {:action => :create} do |f| %>
    <div class="form-group has-icon">
      <%= f.label :image, "商品画像" %><br />
      <%= f.file_field :image, accept: "image/*" %>
    </div>
    <div class="form-group has-icon">
      <%= f.label :name, "商品名" %>
      <%= f.text_field :name, class:"form-control" %>
    </div>
    <div class="form-group has-icon">
      <%= f.label :introduction, "商品説明" %>
      <%= f.text_area :introduction, class:"form-control" %>
    </div>
    <div class="form-group has-icon">
      <%= f.label :genre_id, "ジャンル" %><br />
      <%= f.select :genre_id, [["ケーキ", "1"], ["キャンディ", "2"]], include_blank: "選択して下さい" %>
    </div>
    <div class="form-group has-icon">
      <%= f.label :price, "値段(税抜き)" %>
      <%= f.text_field :price, class:"form-control" %>
    </div>
    <div class="form-group has-icon">
      <%= f.radio_button :is_active, :on_sale, checked: "checked"%>
       <%= f.label :sales_status, "販売中", {value: :"0", style: "display: inline-block;"} %>
       <%= f.radio_button :is_active, :off_sale %>
       <%= f.label :sales_status, "販売停止", {value: :"1", style: "display: inline-block;"} %>
    </div>
    <%= f.submit "新規登録", class:"btn btn-success" %>
  <% end %>
  </div>
  </div>
  </div>

app/views/admin/items/show.html.erb
<div class="container">
	<div class="row">
	<div class="col-lg-3">
		<h5>商品詳細</h5>
	</div>
	</div>
	<div class="row">
	<div class="col-lg-offset-1 col-lg-4">
		<%= image_tag @item.image, size: "300x200" %>
	</div>
	<div class="col-lg-6">
	<dl class="dl-horizontal">
		<dt>商品名</dt><dd><%= @item.name %></dd><br>
		<dt>商品説明</dt><dd><%= @item.introduction %></dd><br>
		<dt>ジャンル</dt>
		 <dd>
		  <% genre = Genre.find(@item.genre_id) %>
		  <%= @genre.name %>
		 </dd><br>
		<dt>税込価格（税抜価格)</dt><dd><%= @item.add_tax_price.to_s(:dalimited) %>（<%= @item.price %>）円</dd><br>
		<dt>販売ステータス</dt>
		<%if @item.is_active == true %>
				<dd>販売中</dd>
		<% else %>
				<dd>販売停止中</dd>
		<% end %><br>
	</dl>
	</div>
	</div>
	<div class="row">
		<div class="col-lg-offset-3 col-lg-9">
			<%= link_to '編集する', edit_admin_item_path(@item), class: "btn btn-success" %>
		</div>
	</div>
</div>