config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}
  devise_for :customers, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

 
 namespace :admin do
   get  "/" => "homes#top"
   resources :items, only: [:index, :new, :create, :show, :edit, :update]
   resources :genres, only: [:index, :create, :edit, :update]
   resources :customers, only: [:index, :show, :edit, :update]
   resources :orders, only: [:show, :update]
   resources :ordered_products, only: [:update]
 end
 scope module: 'public' do
  get "/" => "homes#top"
  get "/about" => "homes#about", as: "about"
 resources :items, only: [:index, :show]
 get "/customers/my_page" => "customers#show"
 get "/customers/information/edit" => "customers#edit"
 patch "/customers/information" => "customers#update"
 get "/customers/unsubscribe" => "customers#unsubscribe" #顧客の退会確認画面
 patch "/customers/withdrawal" => "customers#withdrawal", as: "withdrawal_customers"#顧客の退会処理(ステータスの更新)
 put "/customers/withdrawal" => "customers#withdrawal"
 resources :cart_items, only: [:index, :update, :create, :destroy]
 delete "/cart_items" => "cart_items#destroy_all" #カート内商品データ削除(全て)
 resources :orders, only: [:new, :create, :index, :show]
 post "/orders/confirm" => "orders#confirm" #注文情報確認画面
 get "/orders/complete" => "orders#complete" #注文完了画面
 resources :addresses, only: [:index, :edit, :create, :update, :destroy]
end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
 belongs_to :item
 belongs_to :customer
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :addresses, dependent: :destroy
  has_many :order_informations, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  def name
    last_name + first_name
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :ordered_products, dependent: :destroy
  belongs_to :genre
  has_one_attached :image
  def add_tax_price
        (self.price * 1.08).round
  end
end

app/models/order_information.rb
class OrderInformation < ApplicationRecord
  belongs_to :customer
	has_many :ordered_products, dependent: :destroy
	
	enum method_of_payment: { クレジットカード: 0, 銀行振込: 1}
	enum status: { 入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4}
end

app/models/ordered_product.rb
class OrderedProduct < ApplicationRecord
  belongs_to :item
  belongs_to :order_information
  
  enum making_status: {製作不可: 0, 製作待ち: 1, 製作中: 2, 製作完了: 3}
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
  	@genres = Genre.all
  end
  
  def create
    @genre = Genre.new(params_genre)
  	if @genre.save
  		redirect_to admin_genres_path
  	else
  		@genres = Genre.all
  		render "admin/genres/index"
  	end
  end
  
  def edit
    @genre = Genre.find(params[:id])
  end
  
  def update
    @genre = Genre.find(params[:id])
    if @genre.update(params_genre)
        
      redirect_to admin_genres_path
    else
      render "admin/genres/edit"
    end
  end
  
  private
  def params_genre
    params.require(:genre).permit(:name, :status)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @order_informations = OrderInformation.all
    @ordered_products = OrderedProduct.all
  end  
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.page(params[:page])
  end
  
  def new
    @item = Item.new
  end
  
  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item)
    else
      render :new
    end
  end
  
  def show
    @item = Item.find(params[:id])
    @genre = Genre.find(@item.genre_id)
  end
  
  def edit
    @item = Item.find(params[:id])
  end
  
  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path
  end
  
  private
  def item_params
    params.require(:item).permit(:name, :genre_id, :price, :is_active, :image, :introduction)
  end
  def params_genre
    params.require(:genre).permit(:name, :status)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order_information = OrderInformation.find(params[:id])
    @ordered_products = OrderedProduct.all
  end
  
  def update
    @order_information = OrderInformation.find(params[:id])
    @order_information.update(order_params)
    if params[:order][:status] == "入金確認"
         @ordered_products.each do |ordered_products|
            ordered_products.update!(create_status: 1)
         end
    end
      redirect_to admin_order_path(@order)
  end
  
  private
   def order_params
      params.require(:order).permit(:customer_id, :shipping_postal_code, :shipping_address, :shipping_name, :method_of_payment, :status, :postage, :billing_amount)
   end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 def after_sign_in_path_for(resource)
        case resource
        when Admin
            root_path
        when Customer
            customers_my_page_path # ログイン後に遷移するpathを設定
        end
 end

  
  private

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,keys:[:email])
    end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
 <header>
  
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div style="color:white">
        <h3>ながのケーキ</h3>
      </div>
     
    
       <% if current_customer %>
      <div style="color:white">ようこそ<%= current_customer.last_name %>さん!</div>
       <% end %>
    

      <div class="d-flex justify-content-end">
        <% if customer_signed_in? %>
          <li class="nav-item">
            <%= link_to "マイページ", customers_my_page_path %>
          </li>
          <li class="nav-item">
            <%= link_to "商品一覧", items_path %>
          </li>
          <li class="nav-item">
            <%= link_to "カート", cart_items_path %>
          </li>
          <li class="nav-item">
            <%= link_to "ログアウト", destroy_customer_session_path(current_customer), method: :delete %>
          </li>
        <% elsif admin_signed_in? %>
          <li class="nav-item">
            <%= link_to "商品一覧", admin_items_path %>
          </li>
          <li class="nav-item">
            <%= link_to "会員一覧", admin_customers_path %>
          </li>
          <li class="nav-item">
            <%= link_to "注文履歴一覧", admin_url %>
          </li>
          <li class="nav-item">
            <%= link_to "ジャンル一覧", admin_genres_path %>
          </li>
          <li class="nav-item">
            <%= link_to "ログアウト", destroy_admin_session_path, method: :delete %>
          </li>
          <div id="nav-search">
            <%= form_tag root_path, :method => 'get' do %>
              <p>
                <%= text_field_tag :search, params[:search] %>
                <%= submit_tag "検索", :name => nil %>
              </p>
            <% end %>
          </div>
        <% else %>
          <li class="nav-item">
            <%= link_to "About", about_path %>
          </li>
          <li class="nav-item">
            <%= link_to "商品一覧", items_path %>
          </li>
          <li class="nav-item">
            <%= link_to "新規登録", new_customer_registration_path %>
          </li>
          <li class="nav-item">
            <%= link_to "ログイン", new_customer_session_path %>
          </li>
        <% end %>
      </>
    </nav>
  
</header>
  <div class="body">
  <div class="container">
    <%= yield %>
  </div>
  </body>
 
</html>